// See https://aka.ms/new-console-template for more information

using Spectre.Console;

Console.WriteLine(
"""
Accusam et et at nonumy diam amet quis consetetur est eirmod sadipscing et diam nonumy. Accusam ut ipsum rebum sadipscing dolore. Feugiat dolor magna stet. Tempor nulla et sanctus dolor esse vero.

Magna lorem et dolor in feugiat elitr diam exerci blandit accusam sit nonumy nulla ea dolore assum sit. Sed volutpat eros ipsum diam kasd et justo. Et sed placerat nulla placerat accumsan. Dolor justo clita stet invidunt volutpat lorem sea. Hendrerit ut nonumy labore dolore aliquam. Kasd lorem nonumy takimata ut est et diam sea no. At dignissim diam feugiat sadipscing lorem sit justo autem diam at ipsum in. Tempor invidunt ut voluptua sed invidunt consetetur sed diam. Lorem nobis dolore ipsum sed lorem dolore clita magna no gubergren esse consequat voluptua elitr nonumy et. At est invidunt takimata dolores nonumy ipsum invidunt consectetuer rebum eu. Ipsum vel sadipscing sit duis. Stet ipsum sanctus zzril magna stet et kasd sed autem et eros. Nonumy justo nisl lorem eos facilisis dolor. Duis illum ipsum et lobortis sit sea dolores et nibh diam eos ea diam ea consetetur. Ad diam eos sanctus luptatum esse invidunt no aliquyam sed eirmod et consectetuer et.

Sadipscing dolor rebum facilisi aliquip et iriure no amet ut justo quod. Justo clita illum clita in tincidunt ut takimata sed erat magna duo diam diam. Aliquam no sed at lobortis dolores facilisi gubergren accusam ut elitr consequat eu rebum nibh sit ut sanctus ea. Erat est rebum lorem rebum nostrud sea ea ut labore dolor kasd ullamcorper illum sea ut aliquyam. Invidunt kasd magna ut vel sanctus sit vero amet sadipscing volutpat erat dolore et sea duo et. Sit sea dolore consetetur no quod ipsum tempor dolores ex consetetur dolore. No iriure euismod at eos stet sadipscing at sed. In praesent elit ut sed. Stet lorem nonumy dolores sadipscing suscipit magna sed sed. Eirmod magna dolore nonumy justo nulla duo duo et. Est ut labore tempor sed nonumy lorem liber nonumy amet gubergren diam stet vel lorem consequat sanctus in diam. Rebum elitr consequat odio at rebum rebum soluta dolor et labore magna sea takimata enim clita justo. Doming lorem et amet nulla enim mazim kasd sit erat. Et accumsan et. Iusto et stet sit ipsum facilisis sed at clita ipsum lorem clita erat ipsum takimata ea elitr feugiat. Dolore hendrerit ipsum lorem labore duo rebum ea stet vel blandit eu.

Gubergren et odio tempor kasd est eos dolores aliquyam. Sea feugiat ipsum rebum nibh kasd ipsum sed minim labore sadipscing. Ut consequat erat dolore amet ea et eos amet nulla ipsum ipsum dolor lorem. Erat magna magna consequat duis clita aliquyam aliquyam magna illum labore. Dolor sanctus eros et augue labore ea amet. Et rebum ipsum. Dolor at dolore consequat magna et kasd feugiat laoreet justo gubergren. Vero dolor sit feugiat est. Et lorem no ipsum et gubergren hendrerit sit diam invidunt lorem consectetuer esse molestie et. Ea suscipit dolor. Iriure et eos sed. Diam ut sed nonumy accumsan rebum esse adipiscing dolores sit at illum est exerci iusto facilisi minim. Vero et consetetur ea dolor est lorem erat sit illum sea. Labore voluptua zzril ipsum vel duis. Iriure duis eos amet ipsum diam mazim nonummy tempor. Dolor sed diam diam ipsum ipsum tempor dolores nonumy voluptua voluptua ut sit duo. Kasd ut nonummy amet lorem dolor gubergren amet sadipscing accusam dolor dolor et et kasd ipsum dolor commodo sit. Et ut est magna. Tincidunt invidunt vero ipsum diam te duo est diam suscipit ut clita.

Gubergren tempor magna dolor takimata nobis dolor eirmod odio nostrud diam sea dolor doming justo et elitr consequat duis. Vel ea tempor eros adipiscing feugiat velit sit sed. Gubergren tempor justo blandit quis stet. Tempor dolore commodo elit erat lorem dolor no justo no velit erat stet no sanctus magna tempor facilisi. Amet ut illum dolor ea sit sed dolor dolore sed nonumy et ut. In nonumy amet dolor kasd et vel nonumy duo lorem clita augue eum. Sed est diam et clita et augue ipsum euismod ut et iriure tempor dolor amet justo aliquyam gubergren dolor. Accusam voluptua takimata amet vero iriure no kasd est dolore sed ut et stet invidunt. Labore takimata et justo tincidunt elitr augue ea dolor amet erat et amet dolore. Gubergren no sed takimata lobortis. Iriure accusam lorem at. Magna consetetur takimata dolor vulputate hendrerit et consectetuer ut vero.

Iusto sed sit et et amet rebum. Et ut dolor dolores diam ea sanctus dolore et hendrerit. Ipsum eum diam clita eirmod tation est clita. Dolores adipiscing sed ad sed ut et erat sea eos vulputate. Vero nulla accusam laoreet. Vulputate velit et. Labore lorem veniam magna ea eos consequat dolores takimata tempor dolore amet no sadipscing soluta sed. Te justo nostrud diam accumsan diam. Sanctus amet dolore sit lorem sed eu amet nostrud et labore et duo nonumy et sit sed clita labore. Ea aliquyam lorem.

Amet stet magna magna stet. Consetetur accusam nostrud et diam. Iriure consectetuer dolor suscipit et vero feugait gubergren et eos consetetur iusto duo justo magna exerci. Invidunt consetetur nulla doming labore nisl consetetur amet vel eum vero suscipit kasd vero est. No erat autem elit. Duis sanctus velit consetetur elit sed justo facilisis soluta minim vel ut. Vero exerci eum quis kasd erat at. Et sit invidunt amet in duo. Lorem no nonumy nobis vero sea iriure nonumy sed eleifend ut at at consetetur amet labore diam esse. Eum et takimata magna dolores qui diam. Ipsum no molestie tempor sanctus at magna vel. Ut sit kasd takimata invidunt et ut stet voluptua odio. Quod veniam rebum sadipscing stet dolore erat vulputate et at facer dolore et sed velit. Et vero erat dolor consetetur exerci aliquam at feugiat nostrud lorem iriure sit lorem duo vulputate dolor.

Eos veniam nonumy rebum vero takimata nostrud velit dolore dolore rebum quis erat wisi at aliquyam diam feugiat. Et ut sit wisi dolore clita sea. In stet doming lorem labore est sanctus et vel consetetur sadipscing aliquyam diam lorem eos sit eum ea ipsum. Magna magna at. Gubergren elitr accumsan eirmod sed sit blandit amet eu magna ea eos est et. Sadipscing eos lorem no tempor sit tempor lorem duo clita facilisis eos sea stet dolore consetetur et. Labore diam vero feugiat duo eirmod velit no ipsum lorem. Assum amet et delenit tincidunt dolore dolor et aliquyam esse ea luptatum elitr est voluptua qui eos gubergren sea. Invidunt amet soluta eirmod elitr ut duis lorem euismod elitr duis ipsum odio diam. Kasd kasd nulla dolor feugiat sit clita diam ea dolor at lorem sed. Justo minim option sed. Eos in et sed et nonumy sed erat et takimata diam dolores aliquyam. Voluptua rebum nulla wisi voluptua clita dolor vero est ipsum. Dolores dolore et kasd at erat dolor takimata diam duo lorem facilisis commodo est rebum. Ipsum nostrud praesent esse ipsum sit dolor consequat sed. Dolor eos erat ipsum ipsum lorem augue no suscipit sea sea justo consequat nonummy erat gubergren. Autem odio invidunt takimata. Rebum nonummy tempor dolore eirmod ea et et no est dolore.

Vero sed stet et. Sit quod erat et. Nisl stet vero no consetetur sadipscing lorem clita in labore. Gubergren accusam accusam eirmod et option elitr dolore diam volutpat tempor. Iriure est et nonumy sed erat. Et elitr sed dolore eos odio rebum sanctus eos facilisis sed quod nonumy voluptua amet ea vulputate elitr liber. Dignissim sit ut sed vero dolores aliquyam imperdiet lorem consetetur lorem voluptua at nulla nonumy ad duo. Ipsum duis sit sadipscing ipsum justo ipsum diam rebum vero ut diam iriure.

Lorem molestie dolore takimata consectetuer sea facilisi sed dolore ut sed feugait sit justo. Vulputate dolore sed et consetetur no et diam dolor et elitr. Ipsum velit sit rebum accusam takimata.

Sadipscing takimata sanctus aliquip erat vero aliquyam dolore. At sed invidunt hendrerit ad tempor ipsum voluptua eos ipsum vel lorem ut labore sed lorem consetetur. Ea diam accusam eros ipsum et. Voluptua nulla vel sed diam nonumy assum. Duo dolor odio at sanctus est dolor sadipscing tation. Est lorem diam ut et et rebum invidunt volutpat erat in et lorem at et.

Voluptua sea ipsum et autem consetetur molestie diam exerci ipsum lorem aliquyam erat. Sit stet clita ipsum stet. Stet et erat rebum ipsum blandit dolores eos aliquyam in sit est vero. Amet ut gubergren dolore sed. Eleifend nulla sit stet elit minim dolor et eum sea ullamcorper autem. Ut vero nisl nulla labore aliquyam aliquyam diam stet gubergren et tation consetetur rebum suscipit in clita dolor dolor. Dignissim sadipscing facer voluptua et lorem est nobis dolor sit labore invidunt justo ipsum diam consequat sed. No ut diam labore dolor odio diam ut est dolore minim lorem amet. Gubergren diam est diam soluta tincidunt autem labore quod duis erat velit odio labore eirmod. Diam eirmod congue iriure iriure amet aliquyam invidunt sed ut amet dolore. Et diam eu doming ut gubergren dolore elitr quis duo. Velit at laoreet delenit lorem dolores lorem elitr invidunt no takimata accumsan sit et eum rebum. Invidunt consequat eu elitr eirmod takimata vero takimata dolore diam erat vero sanctus accusam. Dignissim lorem qui aliquip eirmod sit et vulputate ut hendrerit. Ut consetetur consequat aliquyam lorem feugait rebum te takimata velit justo at amet lorem invidunt et. Amet dolor justo et eirmod accumsan justo et facilisi eirmod voluptua sanctus ipsum sit dolor et. Diam facilisis eos sit aliquip. In aliquyam veniam kasd ea no dolores et ipsum at vero stet tation accumsan erat dolor accusam delenit. Diam consequat lorem esse et in laoreet eos nonumy feugait.

Est in ut takimata lorem sadipscing stet qui kasd facer duo vero magna voluptua. Sea euismod dolore sadipscing nostrud sed odio eos no. Hendrerit et duo eum invidunt sed kasd aliquyam in. Iusto vero amet erat eirmod takimata consetetur justo. Qui aliquyam tation imperdiet at ea clita sanctus luptatum dolore eos labore duo at wisi sea dolores. Nonumy vero stet takimata. Tation eirmod magna sit clita lorem. Dolor labore molestie dolore vulputate in ipsum facilisis elitr minim in est erat ipsum wisi in et. Minim et accusam sit sanctus nostrud clita kasd ipsum lorem sea amet rebum.

Doming rebum nulla delenit ut. Voluptua nonumy labore ipsum sea magna sea imperdiet congue nonumy wisi amet dolor diam magna. Takimata consetetur at et consetetur dolor ipsum aliquyam ipsum praesent in ut labore.

Eos labore aliquyam vulputate dolore erat sadipscing ipsum sit est labore iusto kasd vulputate labore clita diam nisl. Nulla rebum velit ea sea soluta aliquip dolore est vero eos tincidunt at ea at kasd. Lobortis sed eirmod lorem dolor aliquyam erat lorem facilisis duo no option. Facer accusam amet vulputate in nulla dolor justo lorem eirmod dolor ipsum lorem mazim suscipit lorem suscipit exerci et. Sadipscing ut dolor. Clita gubergren ut quis adipiscing sed adipiscing imperdiet sit elitr labore dolores nibh et. Dolor nonummy placerat et lorem invidunt eos dolor erat hendrerit sit at sed tation. Esse duo consetetur suscipit rebum magna nulla hendrerit justo. Accusam consectetuer invidunt kasd. Sanctus tempor et dolor duo et sit nam. Justo magna dolores vel et adipiscing dolor accusam ut aliquyam dolore et vero vero sadipscing. Invidunt sit eos nonumy consequat justo stet dolore stet sed rebum et.

Sit ipsum eu labore et et ea lorem dignissim nisl vero dolore ea aliquyam no takimata. Magna facer te. Ut consequat volutpat vero ipsum duo et justo takimata lorem sed rebum tincidunt veniam illum est diam diam facilisis. Eirmod magna justo rebum qui cum takimata sed. Luptatum labore justo ut gubergren ea invidunt clita sed rebum rebum wisi augue dolore et. Dolores et suscipit dolore accusam elitr sed kasd ut sed velit vero ea no justo kasd. Aliquyam in invidunt no. Erat et feugiat eum duis dolore lorem sit tincidunt ad. Ex commodo illum labore luptatum duo accumsan exerci. Vel ea gubergren nonummy sed et consetetur lorem esse volutpat in stet et et iusto. Magna diam sadipscing nibh diam eirmod justo et et lorem at. Voluptua gubergren sit dolore. Ipsum labore ipsum aliquyam autem et eleifend et consetetur euismod. Sed hendrerit labore kasd no et lobortis diam wisi magna doming quod sadipscing tempor et nonumy elitr takimata nonummy. Et sea in et invidunt justo lorem vel duis tation sed dolor. Kasd dolore lorem ea no erat dolor magna est invidunt duis sed feugait.

At et accumsan gubergren invidunt dolor ut et lorem dolores magna no. Eos rebum lorem ipsum sea clita gubergren sanctus sadipscing ad. Sed at lorem amet dolor voluptua elitr. Sea vel sea sed dolor justo ut dolores. Ipsum kasd ea sed molestie wisi commodo sadipscing adipiscing nostrud et ipsum. Imperdiet duis voluptua diam dolore gubergren et ut te sanctus elitr eirmod sit ut. Accusam dolor labore elitr gubergren lorem takimata et rebum. No gubergren eirmod sea no ut feugait dolor. Vero sea molestie clita stet at no autem takimata dolore takimata suscipit ipsum nibh justo velit facilisis tincidunt at. Ut dolor sit clita et dolor lorem est diam consequat. Elit elitr sed eum. Tempor nonumy sed et sit. Justo amet takimata et et. Et lorem lorem kasd labore feugait eirmod lobortis at et nostrud erat at lorem ea. Sanctus elitr volutpat nostrud et sed. Velit elitr sea amet et ipsum dolor est invidunt. Dolore invidunt vero dolore et rebum et diam. Molestie et sit duo nostrud dolor cum nostrud consetetur amet sit eos et sed magna feugait justo.

Est ut invidunt consectetuer kasd amet facilisi duo amet hendrerit diam at sit aliquam diam at sit sed vero. Dolor nihil et in et amet accusam dolor consetetur dolore eros dolor velit. Invidunt sed gubergren ea labore et dolores erat elitr vero lorem est. Clita et rebum vel amet consetetur ut diam voluptua dolor amet erat. Takimata takimata suscipit accumsan clita elitr lorem. Molestie lorem soluta dignissim sadipscing ut option quis. Sit est dolores eirmod feugait sadipscing aliquyam sit diam lorem dolor eos tincidunt kasd iriure. Kasd ea iriure assum praesent amet kasd sit eos dolor tempor facilisis lorem. Elitr sed diam invidunt sadipscing sed clita suscipit et dolor euismod eos volutpat nonumy sea lorem sanctus praesent takimata. Et ea lorem accusam nisl sanctus consetetur et rebum sit et et consequat et clita justo. Placerat nonumy erat exerci dolore dolore augue gubergren dolor ullamcorper justo et est placerat. Erat ipsum sea placerat eos est commodo eirmod labore amet. Accusam magna elitr est ex diam nonumy elitr et nostrud sea eros mazim ipsum sed kasd clita ea. Nulla gubergren ipsum at elit sit. Assum eum vero consetetur sit molestie ad dolore clita eu lorem invidunt no. Vulputate stet elitr sit ipsum eos labore sanctus magna iriure velit lorem sanctus est. Sit accumsan in commodo. Takimata sadipscing duo sanctus vero eos dolore no vulputate eum placerat iusto vero feugiat et dolor magna feugiat. Wisi clita amet rebum euismod et aliquyam eos sea praesent sed elitr.

Est nonumy amet erat ipsum et invidunt vero. Lorem tation nonumy nulla duo labore eirmod illum et dolor vero invidunt elitr eos sanctus. Congue wisi sit diam elitr erat dolor vel amet duo possim dolore dolor consetetur ut sit placerat accusam. Et in gubergren kasd et sea et ullamcorper amet dignissim dolore stet et et et.

Laoreet labore lorem accusam est feugait minim amet. Iusto magna tation et sed duis accusam et invidunt ea dolor dignissim ipsum et sadipscing. Takimata elitr imperdiet sanctus ut augue dolore velit dignissim hendrerit. Eos lorem tempor aliquyam erat sed no. Dolor lorem eos tincidunt sea sadipscing kasd sit velit ut duo at vulputate diam esse dolore. Et amet vulputate gubergren ipsum et stet lorem. Dolore sea lorem molestie nostrud. Aliquyam clita takimata tempor labore labore esse clita clita dolores ea dignissim commodo erat lorem dolore. Diam et gubergren ea ipsum kasd.

Invidunt ut ipsum. Ipsum et delenit consetetur. Justo et dolore aliquyam praesent dolores ea. Nostrud dolore commodo dolore ex ut dignissim lorem doming elit ut lorem diam. Sit ipsum vero. Voluptua dolor dolores no tempor commodo consetetur et delenit sed labore et odio. At invidunt dolore blandit aliquam ullamcorper. Et aliquip veniam nibh amet at amet lorem et et erat labore accusam in rebum ea. Vero sit elitr vel et in et exerci at. Et lorem et sit ipsum dolores aliquyam. Ut labore ex accusam facilisis ipsum justo aliquyam erat. Facilisis dolor consetetur veniam hendrerit et consetetur aliquam enim lorem et no. Rebum at esse voluptua amet dolore eos amet est. Dolores aliquyam consetetur. Lorem mazim nostrud at et justo nulla et takimata dolor diam amet sed ut et et at. At nisl vel amet sed nonumy duo diam rebum no takimata te. Duis sit et diam voluptua sanctus ut vero nonumy et dolore consectetuer.

Dolore amet illum minim tempor amet feugiat lorem suscipit ipsum tincidunt nobis tincidunt doming ipsum sanctus odio takimata sed. At tempor consetetur. Sanctus rebum labore amet ea molestie justo te dolor ipsum ea dolore rebum wisi eirmod kasd. Consetetur sed ipsum. Consetetur ea magna voluptua dolore et at ipsum duo nibh et sit amet. Sea et amet est duo dolore dolore autem accusam nibh. Elitr takimata tempor voluptua accusam erat. Sit tempor adipiscing stet ipsum nam dolor accusam dolor nulla ut elitr amet. Vel no rebum amet lorem lobortis et zzril ipsum iriure erat et gubergren in gubergren. Nulla dolor dolore qui est augue at consetetur rebum takimata justo diam. Takimata erat erat. Magna erat dolor diam. Dolores lobortis takimata commodo takimata. Illum nobis sit gubergren amet invidunt. Aliquam gubergren magna. Justo ut et magna feugiat lorem takimata eros diam et lorem. Suscipit elit erat amet duo no et erat et takimata vero. Illum gubergren gubergren dolor elit erat sed justo rebum kasd diam sit dolor commodo tempor. Ipsum accusam gubergren labore illum.

Ipsum consequat eos no sadipscing ea illum. Stet eum voluptua amet et nibh takimata sadipscing sadipscing voluptua magna exerci autem lobortis dolores iriure. Sadipscing est lorem lorem eos eos nostrud est eos amet tempor et eirmod. Illum aliquyam diam ea dolore ad nihil. At et sed eos no ipsum et vero dolor sed sit dolor amet rebum. Rebum nonumy vero adipiscing enim feugiat lorem tempor duo. Consetetur magna adipiscing tempor hendrerit ipsum et sed voluptua. Sea at duo rebum odio et lorem dolor. Dolor volutpat ex diam diam stet at gubergren sed labore qui. Ut gubergren et rebum facer sit stet justo rebum erat stet eos duis stet. Dolor in sed eum consectetuer vel sed lorem eos duis sadipscing lorem vero augue. Aliquyam sea sea aliquyam. Veniam illum ea et. Clita stet no ut aliquip diam possim et magna et ad amet nulla et duis sed. Dolore accusam vel ipsum duis feugait et vero est et feugiat sanctus ut lorem sanctus stet justo consequat labore. Tempor velit dolor et ut ut elitr amet hendrerit labore invidunt. Consetetur ullamcorper nonumy sed ipsum est duo. Iusto consetetur eleifend nibh kasd est sit duo eirmod tempor clita justo at dolore justo sadipscing invidunt takimata. Kasd dolores voluptua lorem et dolore praesent labore duo ea sit amet dolores et aliquyam et.

Est sanctus nobis nonumy. Takimata dolor ipsum esse labore hendrerit diam minim et sea amet et ipsum adipiscing diam. Labore sed accusam erat dolor eirmod at dolor. Augue aliquam at. Magna dolor dolor nonumy gubergren ipsum ipsum et amet blandit at sed volutpat sea. Eos consequat diam. Est elitr vulputate et nonummy no et molestie eros zzril esse lorem sed ea sadipscing. Rebum erat dolore dolor erat eirmod et nonumy gubergren rebum sit lorem erat sed. Magna odio amet lorem magna no rebum stet magna ut. Consetetur at diam rebum ut stet at. Ipsum justo facilisis dolores elitr dolores nisl invidunt vero sit. Duo elitr sit tempor rebum dolore diam kasd erat ut ea liber sit eos consequat minim et te nulla. Accusam erat sit invidunt diam takimata nonumy at sanctus iriure eos nonumy diam et amet iriure. Aliquyam augue ea consetetur molestie sit nihil euismod blandit. Consetetur duis lorem eirmod laoreet minim et ut accumsan sit duis magna sea duis et velit nobis clita at.

Lorem sanctus duo diam dolore lorem sit illum. Gubergren facilisis laoreet feugiat consetetur nulla aliquip exerci gubergren duis ullamcorper ut sed sit consetetur exerci. Ipsum clita rebum stet ipsum amet consetetur sed diam facilisi tempor kasd. Ipsum accusam tempor nostrud erat accusam tempor kasd praesent et.
""");

var table = new Table();

table.AddColumn("Module");
table.AddColumn("Duration");
table.AddColumn("Status");
table.AddColumn("Start");
table.AddColumn("End");
table.AddColumn(string.Empty);

for (var i = 0; i < 100; i++)
{
    table.AddRow(
        $"[cyan]{Guid.NewGuid():N}[/]",
        $"{Guid.NewGuid():N}",
        $"{Guid.NewGuid():N}",
        $"{Guid.NewGuid():N}",
        $"{Guid.NewGuid():N}",
        $"{Guid.NewGuid():N}");
            
    table.AddEmptyRow();
}

Console.WriteLine();
AnsiConsole.Write(table);
Console.WriteLine();